"""diagram concept link

Revision ID: 4aa6ca39589e
Revises: 5b64d8a3daee
Create Date: 2026-07-16 06:24:04.668868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '4aa6ca39589e'
down_revision: Union[str, None] = '5b64d8a3daee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagrams', sa.Column('concept_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_diagrams_concept_id'), 'diagrams', ['concept_id'], unique=False)
    op.create_foreign_key(None, 'diagrams', 'concepts', ['concept_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'diagrams', type_='foreignkey')
    op.drop_index(op.f('ix_diagrams_concept_id'), table_name='diagrams')
    op.drop_column('diagrams', 'concept_id')
    # ### end Alembic commands ###
