"""branch free chat

Revision ID: e42559a466ca
Revises: 4aa6ca39589e
Create Date: 2026-07-16 10:33:45.514882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = 'e42559a466ca'
down_revision: Union[str, None] = '4aa6ca39589e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('concept_id', sa.Integer(), nullable=True))
    op.alter_column('branches', 'parent_block_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_branches_concept_id'), 'branches', ['concept_id'], unique=False)
    op.create_foreign_key(None, 'branches', 'concepts', ['concept_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.drop_index(op.f('ix_branches_concept_id'), table_name='branches')
    op.alter_column('branches', 'parent_block_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('branches', 'concept_id')
    # ### end Alembic commands ###
